"""
处理相关常量
"""


class ProcessingConstants:
    """处理相关常量"""
    
    # 文件处理
    MAX_THRESHOLD = 2000
    MIN_THRESHOLD = 500
    SUMMARY_LEN = 200
    KEYWORDS_NUM = 3
    POSTPROCESS_SUMMARY_LEN = 1500
    IMG_MAX_TOKENS = 200
    IMG_OCR_MAX_TOKENS = 2000
    MAX_TOKENS_MULTIPLIER = 1.3
    MAX_TOKENS_HEADER_MULTIPLIER = 1.5
    MAX_TOKENS_REWRITE_MULTIPLIER = 1.2
    MAX_TOKENS_SUMMARY_MULTIPLIER = 1.2
    MAX_TOKENS_JUDGE = 20
    MAX_TOKENS_TITLE_MULTIPLIER = 200
    MAX_TOKENS_SUBS_MULTIPLIER = 1.2
    MAX_TOKENS_REWRITE_SENTENCE_MULTIPLIER = 1.3
    MAX_TOKENS_QA_MULTIPLIER = 1.5
    MAX_TOKENS_QA_OUTPUT_MULTIPLIER = 1.2
    MAX_TOKENS_QA_OUTPUT_LIMIT = 20
    
    # 图像处理
    IMG_MIN_SIZE = 10 * 1024  # 10KB
    IMG_MAX_SIZE = 5 * 1024 * 1024  # 5MB
    IMG_QUALITY = 100
    IMG_CHUNK_SIZE = 1024 * 1024  # 1MB
    
    # 数据库连接
    DB_CONNECT_TIMEOUT = 30
    DB_POOL_RECYCLE = 1800
    DB_POOL_SIZE = 200
    DB_MAX_OVERFLOW = 500
    
    # 训练参数
    TRAIN_BATCH_SIZE = 16
    MEMORY_K = 2
    MEMORY_LR = 0.001
    MEMORY_BATCH_SIZE = 2
    MEMORY_N_EPOCHS = 3
    MEMORY_MAX_INPUT_LENGTH = 2048
