apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: knowhere

resources:
  - ../base

# 环境特定的配置
configMapGenerator:
  - name: knowhere-config
    behavior: merge
    literals:
      - ENVIRONMENT=dev

# 替换环境变量
replacements:
  - source:
      kind: ConfigMap
      name: knowhere-config
      fieldPath: data.ENVIRONMENT
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - metadata.annotations.nginx\.ingress\.kubernetes\.io/ssl-redirect
      - select:
          kind: Deployment
        fieldPaths:
          - spec.template.metadata.labels.environment

# 环境变量替换
patches:
  - target:
      kind: Ingress
      name: knowhere-ingress
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: apidev.knowhereto.com
      - op: replace
        path: /spec/tls/0/hosts/1
        value: dev.knowhereto.com
      - op: replace
        path: /spec/rules/0/host
        value: apidev.knowhereto.com
      - op: replace
        path: /spec/rules/1/host
        value: dev.knowhereto.com
  - target:
      kind: Deployment
      name: knowhere-web
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: https://apidev.knowhereto.com

