"""add_email_logs_table

Revision ID: 7477484d4936
Revises: a047370dc9a1
Create Date: 2025-11-27 00:05:09.060302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7477484d4936'
down_revision: Union[str, Sequence[str], None] = 'a047370dc9a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email_type', sa.String(length=50), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('template_id', sa.String(length=255), nullable=True),
    sa.Column('template_variables', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_logs_created_at', 'email_logs', ['created_at'], unique=False)
    op.create_index('idx_email_logs_email_type', 'email_logs', ['email_type'], unique=False)
    op.create_index('idx_email_logs_job_id', 'email_logs', ['job_id'], unique=False)
    op.create_index('idx_email_logs_recipient_email', 'email_logs', ['recipient_email'], unique=False)
    op.create_index('idx_email_logs_success', 'email_logs', ['success'], unique=False)
    op.create_index('idx_email_logs_user_id', 'email_logs', ['user_id'], unique=False)
    # 注意：只创建 email_logs 表，不删除其他表
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_logs_user_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_success'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_recipient_email'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_job_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_email_type'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_created_at'), table_name='email_logs')
    op.drop_index('idx_email_logs_user_id', table_name='email_logs')
    op.drop_index('idx_email_logs_success', table_name='email_logs')
    op.drop_index('idx_email_logs_recipient_email', table_name='email_logs')
    op.drop_index('idx_email_logs_job_id', table_name='email_logs')
    op.drop_index('idx_email_logs_email_type', table_name='email_logs')
    op.drop_index('idx_email_logs_created_at', table_name='email_logs')
    op.drop_table('email_logs')
