"""increase_chunk_type_field_length_to_2000

Revision ID: a370fa1c27fc
Revises: 7afbeec4cd27
Create Date: 2025-10-23 15:49:20.386410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a370fa1c27fc'
down_revision: Union[str, Sequence[str], None] = '7afbeec4cd27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_log_created_at', table_name='job_state_audit_logs')
    op.drop_index('idx_audit_log_job_created', table_name='job_state_audit_logs')
    op.drop_index('idx_audit_log_job_id', table_name='job_state_audit_logs')
    op.drop_table('job_state_audit_logs')
    op.alter_column('job_chunks', 'chunk_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=2000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_chunks', 'chunk_type',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.create_table('job_state_audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('from_state', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('to_state', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('transition_reason', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('operator_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('operator_type', sa.VARCHAR(length=20), server_default=sa.text("'system'::character varying"), autoincrement=False, nullable=False),
    sa.Column('transition_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], name='job_state_audit_logs_job_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='job_state_audit_logs_pkey')
    )
    op.create_index('idx_audit_log_job_id', 'job_state_audit_logs', ['job_id'], unique=False)
    op.create_index('idx_audit_log_job_created', 'job_state_audit_logs', ['job_id', 'created_at'], unique=False)
    op.create_index('idx_audit_log_created_at', 'job_state_audit_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###
