"""add_key_mask_to_api_keys

Revision ID: c88943aa1196
Revises: a370fa1c27fc
Create Date: 2025-10-23 16:51:36.197643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c88943aa1196'
down_revision: Union[str, Sequence[str], None] = 'a370fa1c27fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('key_mask', sa.String(length=50), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'key_mask')
    # ### end Alembic commands ###
