"""Initial migration with knowledge_base type field update

Revision ID: f16d6b72dcf8
Revises: 
Create Date: 2025-10-17 17:24:05.052934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16d6b72dcf8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_base', 'type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_comment='内容类型（如PTXT, SUMMARY等）',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_base', 'type',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_comment='内容类型（如PTXT, SUMMARY等）',
               existing_nullable=True)
    # ### end Alembic commands ###
